exclude: ^LICENSE/|\.(ipynb|html|svg)$

ci:
    autofix_prs: false
    autoupdate_schedule: weekly
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: debug-statements
        language_version: python3
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        require_serial: true
        types_or: [python, pyi]
        additional_dependencies: [black==24.3.0]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.11
    hooks:
      - id: vulture
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
