name: Documentation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx-rtd-theme myst_parser
      - name: Sphinx build
        run: |
          sphinx-build doc/source doc/build
      - name: Build HTML
        run: | 
          cd doc/
          make html
      - name: Run ghp-import
        run: | 
          ghp-import -n -p -f doc/build/html
